theme = "synthwave84"

[editor]
line-number = "relative"
indent-guides.render = true

[editor.cursor-shape]
insert = "bar"           # LÃ­nea vertical en modo insert
normal = "block"         # Bloque en modo normal
select = "underline"     # Subrayado en modo select

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"
